# Development-specific Docker Compose overrides
version: '3.8'

services:
  backend:
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000 --debug --reload

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
    stdin_open: true
    tty: true
