version: '3.8'

services:
  backend-test:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - FLASK_ENV=testing
      - DATABASE_URL=postgresql://postgres:postgres@postgres-test:5432/hockey_test
      - SECRET_KEY=test-secret-key
      - MAIL_SUPPRESS_SEND=True
    depends_on:
      postgres-test:
        condition: service_healthy
    volumes:
      - .:/app
    command: python -m pytest tests/ -v --cov=. --cov-report=xml

  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: hockey_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      target: test
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run test -- --coverage --watchAll=false
