"""Add AdminInvitation model

Revision ID: 558e2dc041fe
Revises: f67a63181d9b
Create Date: 2025-10-13 14:15:23.562146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558e2dc041fe'
down_revision = 'f67a63181d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_invitations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_invitations_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_admin_invitations_tenant_id'))

    op.drop_table('admin_invitations')
    # ### end Alembic commands ###
