"""Add default player requirements to tenant

Revision ID: 56ae97798be8
Revises: 
Create Date: 2025-10-03 17:35:51.665758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ae97798be8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_goaltenders', sa.Integer(), server_default='2', nullable=False))
        batch_op.add_column(sa.Column('default_defence', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('default_forwards', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('default_skaters', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('default_skaters')
        batch_op.drop_column('default_forwards')
        batch_op.drop_column('default_defence')
        batch_op.drop_column('default_goaltenders')

    # ### end Alembic commands ###
