"""Add skill_rating to Player model

Revision ID: 5a15d1fcb126
Revises: 7f325d227247
Create Date: 2025-10-07 18:54:24.102973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a15d1fcb126'
down_revision = '7f325d227247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('skill_rating')

    # ### end Alembic commands ###
