"""enhance_invitation_tracking

Revision ID: 7196e0d98f72
Revises: 56ae97798be8
Create Date: 2025-10-05 21:47:11.328760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7196e0d98f72'
down_revision = '56ae97798be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitation_responses_invitation_id'))
        batch_op.drop_index(batch_op.f('ix_invitation_responses_tenant_id'))

    op.drop_table('invitation_responses')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('response_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('response_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_opened_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_bounced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reminder_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('token', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('token_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)
        batch_op.create_unique_constraint('unique_game_player_invitation', ['game_id', 'player_id'])
        batch_op.drop_column('opened_at')
        batch_op.drop_column('sent_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('opened_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('unique_game_player_invitation', type_='unique')
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('token_expires_at')
        batch_op.drop_column('token')
        batch_op.drop_column('reminder_count')
        batch_op.drop_column('reminder_sent_at')
        batch_op.drop_column('email_error')
        batch_op.drop_column('email_bounced_at')
        batch_op.drop_column('email_opened_at')
        batch_op.drop_column('email_delivered_at')
        batch_op.drop_column('email_sent_at')
        batch_op.drop_column('response_notes')
        batch_op.drop_column('response_method')
        batch_op.drop_column('response')

    op.create_table('invitation_responses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('response', sa.VARCHAR(length=10), nullable=False),
    sa.Column('response_method', sa.VARCHAR(length=20), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('invitation_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitation_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitation_responses_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitation_responses_invitation_id'), ['invitation_id'], unique=False)

    # ### end Alembic commands ###
