"""Add email preferences to Player model

Revision ID: 7f325d227247
Revises: 7196e0d98f72
Create Date: 2025-10-07 18:00:23.608159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f325d227247'
down_revision = '7196e0d98f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_invitations', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('email_reminders', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('email_reminders')
        batch_op.drop_column('email_invitations')

    # ### end Alembic commands ###
