"""Add team_number to assignments for team balancing

Revision ID: c6ab400c729c
Revises: 5a15d1fcb126
Create Date: 2025-10-08 08:14:17.198231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ab400c729c'
down_revision = '5a15d1fcb126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_number', sa.Integer(), nullable=True))
        batch_op.alter_column('task_description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('task_description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('team_number')

    # ### end Alembic commands ###
