"""Add invitations_sent_at to games table

Revision ID: f67a63181d9b
Revises: c6ab400c729c
Create Date: 2025-10-12 11:21:05.721277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67a63181d9b'
down_revision = 'c6ab400c729c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitations_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('invitations_sent_at')

    # ### end Alembic commands ###
